FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends bash && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /venv && \
    . /venv/bin/activate && \
    pip install --upgrade pip && \
    pip install internetarchive

ENV PATH="/venv/bin:$PATH"

WORKDIR /app

COPY upload.py /app/upload.py
COPY product_name.txt /app/product_name.txt
COPY upload-entry.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
